config/routes.rb
Rails.application.routes.draw do
  # CMS
  concern :with_datatable do
    post 'datatable', on: :collection
  end

  namespace :admin do
    root to: 'sessions#new'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/', to: 'sessions#destroy'

    resources :users, concerns: [:with_datatable]
    resources :rooms, concerns: [:with_datatable]
  end

  # API Endpoints
  mount API::Base => '/'

  # API Documentation
  mount GrapeSwaggerRails::Engine => '/swagger'

  # Action Cable
  mount ActionCable.server => '/cable'
end

app/models/admin.rb
class Admin < ApplicationRecord
  before_save :check_password

  def authenticate?(password)
    self.password == digest_password(password)
  end

  def check_password
    return unless new_record? || password_changed?
    self.password = digest_password(password)
  end

  private

  def digest_password(password)
    Digest::SHA256.hexdigest(password)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_create_commit :broadcast_message

  def self.get_history(room_id, offset, size=10)
    where(room_id: room_id).order(created_at: :desc).limit(size).offset(offset)
  end

  private

  def broadcast_message
    MessageBroadcastJob.perform_later(self)
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages, dependent: :destroy
  mount_uploader :profile_image, ProfileImageUploader

  validates :username,
            presence: true,
            length: { in: 6..20 },
            uniqueness: { case_sensitive: false }
  validates :email,
            presence: true,
            length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
            uniqueness: { case_sensitive: false }
  validates :first_name, :last_name, presence: true
  validates :password,
            confirmation: true,
            length: { minimum: 6 },
            if: :require_password?

  attr_accessor :reset_code

  before_save :downcase_field, :check_password

  def self.get_user_from_token(token)
    User.find_by(auth_token: token)
  end

  def self.search(term)
    if term
      where('username LIKE :search OR
            email LIKE :search OR
            first_name LIKE :search OR
            last_name LIKE :search',
            search: "%#{term}%")
    else
      all
    end
  end

  def generate_token
    self.auth_token = nil
    loop do
      self.auth_token = new_token
      break unless User.exists?(auth_token: auth_token)
    end
    save!
  end

  def destroy_token
    update(auth_token: nil)
  end

  def valid_password?(password)
    self.password == digest_token(password)
  end

  def reset_expired?
    reset_sent_at < 6.hours.ago
  end

  def valid_reset_code?(code)
    reset_digest == digest_token(code)
  end

  def create_reset_code
    loop do
      self.reset_code = ''
      6.times { self.reset_code << SecureRandom.random_number(9).to_s }
      self.reset_digest = digest_token(self.reset_code)
      break unless User.exists?(reset_digest: self.reset_digest)
    end

    update_columns(reset_digest: self.reset_digest,
                   reset_sent_at: Time.zone.now)
  end

  def send_password_reset_mail
    UserMailer.reset_password(self).deliver_now
  end
  #
  # def online?
  #   Redis.new.get("user_#{id}_online").present?
  # end

  private

  def downcase_field
    username.downcase!
    email.downcase!
  end

  def require_password?
    new_record? || !password.empty? || !password_confirmation.empty?
  end

  def check_password
    return unless new_record? || password_changed?
    self.password = digest_token(password)
  end

  def digest_token(token)
    Digest::SHA256.hexdigest(token)
  end

  def new_token
    SecureRandom.hex(16)
  end
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < ApplicationController
  before_action :require_admin_log_in
  before_action :set_room, only: %i[show edit update destroy]

  def index
  end

  def datatable
    render json: RoomDatatable.new(view_context)
  end

  def show
    @room =Room.find(params[:id])
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to admin_room_path(@room)
    else
      render :new
    end
  end

  def update
    if @room.update(room_params)
      redirect_to admin_room_path(@room)
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to admin_rooms_path
  end

  private

  def room_params
    params.require(:room).permit(:name)
  end

  def set_room
    @room = Room.find(params[:id])
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  def new
    redirect_to request.referer || admin_users_path if admin_logged_in?
  end

  def create
    @admin = Admin.find_by(username: params[:session][:username])

    if @admin&.authenticate?(params[:session][:password])
      log_in @admin
      flash[:success] = 'Log in successfully'
      redirect_to admin_users_path
    else
      flash[:danger] = 'Invalid username or password'
      redirect_to admin_login_path
    end
  end

  def destroy
    log_out
    flash[:success] = 'Log out successfully'
    redirect_to admin_login_path
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin_log_in
  before_action :set_user, only: %i[show edit update destroy]

  def index
    # @users = User.search(params[:search]).order('id').page(params[:page]).per(5)
    # respond_to do |format|
    #   format.html
    #   format.json { render json: UserDatatable.new(view_context) }
    # end
  end

  def datatable
    render json: UserDatatable.new(view_context)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(
      :email,
      :username,
      :first_name,
      :last_name,
      :password,
      :password_confirmation,
      :profile_image
    )
  end

  def set_user
    @user = User.find_by(id: params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Admin::SessionsHelper

  protect_from_forgery unless: -> { request.format.json? }
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
  def log_in(admin)
    cookies.encrypted[:id] = admin.id
  end

  def log_out
    cookies.delete(:id)
    @current_admin = nil
  end

  def current_admin
    @current_admin ||= Admin.find_by(id: cookies.encrypted[:id])
  end

  def admin_logged_in?
    current_admin.present?
  end

  def require_admin_log_in
    redirect_to admin_login_path unless admin_logged_in?
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/rooms/index.html.erb
<div class="container content" >
  <div class="index">
    <%= link_to icon('fas', 'plus'), new_admin_room_path, class:"btn btn-info btn-floating", id: "spacing2"%>
  </div>

  <table class="responsive nowrap table table-hover" id="rooms-datatable" style="width:100%" data-source="<%= datatable_admin_rooms_path(format: :json) %>">
    <thead class="thead-dark">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th data-orderable="false" data-searchable="false"></th>
        <th data-orderable="false" data-searchable="false"></th>
        <th data-orderable="false" data-searchable="false"></th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>

app/views/admin/rooms/show.html.erb
<style type="text/css">
@media only screen and (max-width: 480px) {
    .media {
        padding-right: 0;
        padding-left: 0;
    }
}

@media only screen and (min-width: 481px) {
    .media {
        padding-right: 15%;
        padding-left: 15%;
    }
}
</style>
<div class="container" style="overflow-y: scroll;height: 400px;
margin-top: 5%;">
    <div class="media">
        <div class="media-left">
            <%= image_tag User.third.profile_image.url, class: "ava-show"  %>
        </div>
        <div class="media-body" style="padding: 1%;">
            <h5 class="mt-0" style="font-weight: bold;color: #686880;">Nick Name</h5>
            <p style="color: #030000;">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            </p>
        </div>
    </div>
    <div class="media">
        <div class="media-left">
             <%= image_tag User.first.profile_image.url, class: "ava-show"  %>
        </div>
        <div class="media-body" style="padding: 1%;">
            <h5 class="mt-0" style="font-weight: bold;color: #686880;">Nick Name</h5>
            <p style="color: #030000;">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            </p>
        </div>
    </div>
    <div class="media">
        <div class="media-left">
             <%= image_tag User.first.profile_image.url, class: "ava-show"  %>
        </div>
        <div class="media-body" style="padding: 1%;">
            <h5 class="mt-0" style="font-weight: bold;color: #686880;">Nick Name</h5>
            <p style="color: #030000;">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            </p>
        </div>
    </div>
    <div class="media">
        <div class="media-left">
             <%= image_tag User.first.profile_image.url, class: "ava-show"  %>
        </div>
        <div class="media-body" style="padding: 1%;">
            <h5 class="mt-0" style="font-weight: bold;color: #686880;">Nick Name</h5>
            <p style="color: #030000;">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            </p>
        </div>
    </div>
    <div class="media">
        <div class="media-left">
             <%= image_tag User.first.profile_image.url, class: "ava-show"  %>
        </div>
        <div class="media-body" style="padding: 1%;">
            <h5 class="mt-0" style="font-weight: bold;color: #686880;">Nick Name</h5>
            <p style="color: #030000;">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            </p>
        </div>
    </div>
    <div class="media">
        <div class="media-left">
             <%= image_tag User.first.profile_image.url, class: "ava-show"  %>
        </div>
        <div class="media-body" style="padding: 1%;">
            <h5 class="mt-0" style="font-weight: bold;color: #686880;">Nick Name</h5>
            <p style="color: #030000;">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            </p>
        </div>
    </div>
    <div class="media">
        <div class="media-left">
             <%= image_tag User.first.profile_image.url, class: "ava-show"  %>
        </div>
        <div class="media-body" style="padding: 1%;">
            <h5 class="mt-0" style="font-weight: bold;color: #686880;">Nick Name</h5>
            <p style="color: #030000;">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            </p>
        </div>
    </div>
    <div class="media">
        <div class="media-left">
             <%= image_tag User.first.profile_image.url, class: "ava-show"  %>
        </div>
        <div class="media-body" style="padding: 1%;">
            <h5 class="mt-0" style="font-weight: bold;color: #686880;">Nick Name</h5>
            <p style="color: #030000;">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            </p>
        </div>
    </div>
    <div class="media">
        <div class="media-left">
             <%= image_tag User.first.profile_image.url, class: "ava-show"  %>
        </div>
        <div class="media-body" style="padding: 1%;">
            <h5 class="mt-0" style="font-weight: bold;color: #686880;">Nick Name</h5>
            <p style="color: #030000;">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            </p>
        </div>
    </div>
    <div class="media">
        <div class="media-left">
             <%= image_tag User.first.profile_image.url, class: "ava-show"  %>
        </div>
        <div class="media-body" style="padding: 1%;">
            <h5 class="mt-0" style="font-weight: bold;color: #686880;">Nick Name</h5>
            <p style="color: #030000;">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            </p>
        </div>
    </div>
    <div class="media">
        <div class="media-left">
             <%= image_tag User.first.profile_image.url, class: "ava-show"  %>
        </div>
        <div class="media-body" style="padding: 1%;">
            <h5 class="mt-0" style="font-weight: bold;color: #686880;">Nick Name</h5>
            <p style="color: #030000;">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            </p>
        </div>
    </div>
    <div class="media">
        <div class="media-left">
             <%= image_tag User.first.profile_image.url, class: "ava-show"  %>
        </div>
        <div class="media-body" style="padding: 1%;">
            <h5 class="mt-0" style="font-weight: bold;color: #686880;">Nick Name</h5>
            <p style="color: #030000;">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            </p>
        </div>
    </div>
    <div class="media">
        <div class="media-left">
             <%= image_tag User.second.profile_image.url, class: "ava-show"  %>
        </div>
        <div class="media-body" style="padding: 1%;">
            <h5 class="mt-0" style="font-weight: bold;color: #686880;">Nick Name</h5>
            <p style="color: #030000;">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            </p>
        </div>
    </div>
</div>

app/views/admin/users/_back_to_index.html.erb
<div class="index">
  <%= link_to icon('fas', 'chevron-left'), admin_users_path, class:"btn btn-secondary btn-floating", method: :get %>
</div>

app/views/admin/users/_user_form.html.erb
<%= simple_form_for [:admin, @user] do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :username %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>

  <div class="form-group">
    <%= f.label :profile_image %><br />
    <%= f.file_field :profile_image %>
    <%= image_tag(@user.profile_image.url(:thumb)) if @user.profile_image? %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn-primary float-right" %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="container">
    <div class="index">
        <%= link_to "<", admin_users_path, class:"btn btn-info", id: "pback", method: :get %>
    </div>
    <div class="admin-form">
        <h2 class="form-header">Update user</h2>
        <%= render 'user_form' %>
    </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
    <div class="index">
        <%= link_to "Create", new_admin_user_path, class:"btn btn-info", id: "spacing2"%>
    </div>
    <table class="responsive nowrap table table-hover" role="datatable">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Username</th>
                <!-- <th>Email</th>
                <th>First Name</th>
                <th>Last Name</th> -->
                <th ></th>
            </tr>
        </thead>
        <tbody>
          <%@users.each do |f| %>
          <tr>
            <td><%= f.id%></td>
            <td><%= f.username %></td>
            <td><%= link_to "show" , admin_user_path(f)%>
          </tr>
          <% end %>
        </tbody>
    </table>

</div>

app/views/admin/users/new.html.erb
<div class="container">
    <div class="index">
        <%= link_to "<", admin_users_path, class:"btn btn-info", id: "pback", method: :get %>
    </div>
    <div class="admin-form">
        <h2 class="form-header">Create a new user</h2>
        <%= render "user_form" %>
    </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="avatar">
                <a data-toggle="modal" data-target="#bigProfileImage">
                    <%= image_tag @user.profile_image.url(:preview), class: 'media-object' %>
                </a>
            </div>
        </div>
        <div class="col-md-9" id="res_infor">
            <h2>Profile Info</h2>
            <table class="table table-hover">
                <tbody>
                    <tr>
                        <td>
                            <h6>First Name</h6></td>
                        <td class="text-gray">
                            <%= @user.first_name %>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h6>Last Name</h6></td>
                        <td class="text-gray">
                            <%= @user.last_name %>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h6>Username</h6></td>
                        <td class="text-gray">
                            <%= @user.username %>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h6>Email</h6></td>
                        <td class="text-gray">
                            <%= @user.email %>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h6>Day registered</h6></td>
                        <td class="text-gray">
                            <%= @user.created_at.localtime.strftime('%H:%M:%S %d/%m/%Y') %>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="index">
        <%= link_to "<", admin_users_path, class:"btn btn-info", id: "pback", method: :get %>
    </div>
    <div class="modal fade" id="bigProfileImage" tabindex="-1" role="dialog" aria-labelledby="profileImageLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="profileImageLabel">Profile Image</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <%= image_tag(@user.profile_image.url, class: 'img-fluid') %>
                </div>
            </div>
        </div>
    </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Simple App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Users', admin_users_path, method: :get, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Rooms', admin_rooms_path, method: :get, class: 'nav-link' %>
      </li>
    </ul>

    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_admin.username %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to 'Logout', admin_path,
            method: :delete,
            class: 'dropdown-item' %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bflag CMS</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' if admin_logged_in? %>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
        <%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>